services:
  mysql:
    image: mysql:latest
    container_name: mysql-db
    ports:
      - "3307:3306"
    environment:
      LANG: C.UTF-8
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: my_database
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql_data:/var/lib/mysql
      - ./scrip-base-datos/setup_database_mysql.sql:/docker-entrypoint-initdb.d/setup_database.sql
    networks:
      - mysql_network

volumes:
  mysql_data:

networks:
  mysql_network:
    driver: bridge
